"use client";

import { useEffect, useState } from "react";
import { useApp } from "../../context/AppContext";
import { cacheGet, cacheSet, fetchJson } from "../../lib/client-data";
import { cityOf, codeOf, facultyOf, fmtInt, fmtScore, guideYearOf, historicalQuotaAt, languageOf, num, pick, placedAt, placementYearOf, programOf, quotaAt, rankAt, riskOf, scholarshipOf, scoreAt, scoreTypeOf, trendOf, uniOf, uniTypeOf } from "../../lib/program-utils";
import Modal from "../layout/Modal";
const tone = {
  reach: "border-rose-400/20 bg-rose-400/10 text-rose-300",
  down: "border-rose-400/20 bg-rose-400/10 text-rose-300",
  target: "border-amber-400/20 bg-amber-400/10 text-amber-300",
  flat: "border-amber-400/20 bg-amber-400/10 text-amber-300",
  unknown: "border-slate-500/30 bg-slate-500/10 text-slate-300",
  safe: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
  up: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
};


export default function ProgramDetailModal({ program, onClose, onMessage }) {
  const { profile, preferences, togglePreference } = useApp();
  const [netRows, setNetRows] = useState([]);
  const [netLoading, setNetLoading] = useState(false);
  useEffect(() => setNetRows([]), [program]);
  if (!program) return null;
  const preferred = preferences.some((item) => codeOf(item) === codeOf(program));
  const toggle = () => { const result = togglePreference(program); if (!result.ok) onMessage({ type: "warn", text: result.message }); };
  const loadNetRows = async () => {
    setNetLoading(true);
    try {
      const body = { filters: { kilavuzKodu: codeOf(program), puanTuru: scoreTypeOf(program), universiteId: Number(pick(program, "universiteId", "universite_id")) || null, birimGrupId: Number(pick(program, "birimGrupId", "birim_grup_id")) || null, birimTuruId: Number(pick(program, "birimTuruId", "birim_turu_id")) || null }, page: 0, size: 20 };
      const key = `netler:${JSON.stringify(body)}`;
      const cached = netRows.length ? null : await cacheGet(key);
      const data = cached?.data || await fetchJson("/api/data/netler", { method: "POST", body: JSON.stringify(body) });
      if (!cached?.data) await cacheSet(key, data);
      setNetRows(Array.isArray(data.content) ? data.content : []);
    } catch (error) { onMessage({ type: "error", text: `Net verileri alınamadı: ${error.message}` }); }
    finally { setNetLoading(false); }
  };

  return <Modal open onClose={onClose} title={programOf(program)} subtitle={`${uniOf(program)} · ${cityOf(program)}`} wide>
    <div className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex flex-wrap items-center gap-1.5"><span className="inline-flex min-h-6 items-center rounded-full border px-2.5 py-0.5 text-[10px] font-black uppercase tracking-wide border-sky-400/20 bg-sky-400/10 text-sky-300">{scoreTypeOf(program)}</span><span className={`inline-flex min-h-6 items-center rounded-full border px-2.5 py-0.5 text-[10px] font-black uppercase tracking-wide ${tone[riskOf(program, profile).key] || tone.unknown}`}>{riskOf(program, profile).label}</span><span className={`inline-flex min-h-6 items-center rounded-full border px-2.5 py-0.5 text-[10px] font-black uppercase tracking-wide ${tone[trendOf(program).key] || tone.unknown}`}>{trendOf(program).label}</span></div><div className="flex flex-wrap gap-2"><button className={`inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-xl border px-3.5 py-2 text-sm font-bold transition duration-200 focus-visible:ring-4 focus-visible:ring-cyan-400/15 disabled:cursor-not-allowed disabled:opacity-50 ${preferred ? "border-rose-400/20 bg-rose-500/10 text-rose-300 hover:border-rose-400/40 hover:bg-rose-500/20" : "border-cyan-300/20 bg-gradient-to-r from-cyan-400 to-sky-500 text-slate-950 shadow-lg shadow-cyan-950/25 hover:-translate-y-0.5 hover:from-cyan-300 hover:to-sky-400"}`} onClick={toggle}>{preferred ? "Tercihlerden çıkar" : "+ Tercih listeme ekle"}</button><a className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-xl border px-3.5 py-2 text-sm font-bold transition duration-200 focus-visible:ring-4 focus-visible:ring-cyan-400/15 disabled:cursor-not-allowed disabled:opacity-50 border-slate-700/80 bg-slate-900/70 text-slate-300 hover:border-slate-600 hover:bg-slate-800 hover:text-white" href={`https://yokatlas.yok.gov.tr/${String(pick(program, "birimTuruAdi", "birim_turu_adi") || "").includes("ONL") ? "onlisans" : "lisans"}.php?y=${encodeURIComponent(codeOf(program))}`} target="_blank" rel="noreferrer">Resmî sayfa ↗</a></div></div>
    <div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4 [&>div]:rounded-2xl [&>div]:border [&>div]:border-white/[0.07] [&>div]:bg-gradient-to-br [&>div]:from-white/[0.055] [&>div]:to-transparent [&>div]:p-4 [&_span]:block [&_span]:text-[10px] [&_span]:font-bold [&_span]:uppercase [&_span]:tracking-wide [&_span]:text-slate-500 [&_b]:mt-2 [&_b]:block [&_b]:text-xl [&_b]:font-black [&_b]:text-white"><div><span>{placementYearOf(program)} başarı sırası</span><b>{fmtInt(rankAt(program))}</b></div><div><span>{placementYearOf(program)} taban puan</span><b>{fmtScore(scoreAt(program))}</b></div><div><span>{guideYearOf(program)} kılavuz kontenjanı</span><b>{fmtInt(quotaAt(program))}</b></div><div><span>Başarı sırası koşulu</span><b>{fmtInt(num(pick(program, "minBasariSirasi", "min_basari_sirasi")))}</b></div></div>
    <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr] [&>section>h3]:mb-3 [&>section>h3]:text-sm [&>section>h3]:font-black [&>section>h3]:uppercase [&>section>h3]:tracking-wider [&>section>h3]:text-slate-300"><section><h3>Tamamlanmış yerleştirmeler</h3><div className="w-full overflow-x-auto rounded-2xl border border-white/[0.07] [&>table]:w-full [&>table]:min-w-[620px] [&>table]:border-collapse [&>table]:text-left [&_thead]:bg-slate-950/60 [&_th]:border-b [&_th]:border-white/10 [&_th]:px-4 [&_th]:py-3 [&_th]:text-[11px] [&_th]:font-black [&_th]:uppercase [&_th]:text-slate-500 [&_td]:border-b [&_td]:border-white/[0.06] [&_td]:px-4 [&_td]:py-4 [&_td]:text-sm [&_td]:text-slate-300"><table><thead><tr><th>Yerleştirme yılı</th><th>Başarı sırası</th><th>Taban puan</th><th>Kontenjan</th><th>Yerleşen</th></tr></thead><tbody>{[0, 1, 2, 3].map((offset) => <tr key={offset}><td>{placementYearOf(program, offset)}</td><td><b>{fmtInt(rankAt(program, offset))}</b></td><td>{fmtScore(scoreAt(program, offset))}</td><td>{fmtInt(historicalQuotaAt(program, offset))}</td><td>{fmtInt(placedAt(program, offset))}</td></tr>)}</tbody></table></div></section><section><h3>Program bilgileri</h3><dl className="overflow-hidden rounded-2xl border border-white/[0.07] bg-slate-950/25 [&>div]:grid [&>div]:grid-cols-[minmax(8rem,0.8fr)_1.2fr] [&>div]:gap-3 [&>div]:border-b [&>div]:border-white/[0.06] [&>div]:px-4 [&>div]:py-3 [&>div]:text-sm [&_dt]:text-slate-500 [&_dd]:text-right [&_dd]:font-semibold [&_dd]:text-slate-300">{[
      ["Kılavuz yılı", guideYearOf(program)], ["Son yerleştirme verisi", placementYearOf(program)], ["ÖSYM kodu", codeOf(program)], ["Fakülte / yüksekokul", facultyOf(program)], ["Üniversite türü", uniTypeOf(program)], ["Şehir / ilçe", `${cityOf(program)} / ${pick(program, "ilceAdi", "ilce_adi") || "—"}`], ["Öğrenim dili", languageOf(program)], ["Öğretim türü", pick(program, "ogrenimTuruAdi", "ogrenim_turu_adi") || "—"], ["Burs / ücret", scholarshipOf(program)], ["Öğrenim süresi", pick(program, "ogrenimSuresi", "ogrenim_suresi") ? `${pick(program, "ogrenimSuresi", "ogrenim_suresi")} yıl` : "—"], ["Akreditasyon", pick(program, "akreditasyonAck", "akreditasyon") || "—"], ["Profesör / Doçent / Dr.", `${pick(program, "prof") ?? "—"} / ${pick(program, "doc") ?? "—"} / ${pick(program, "dou") ?? "—"}`]
    ].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></div>
    {Array.isArray(program.kosulList) && program.kosulList.length > 0 && <section className="mt-6 rounded-2xl border border-white/[0.07] bg-slate-950/25 p-4 sm:p-5 [&>h3]:mb-3 [&>h3]:text-sm [&>h3]:font-black [&>h3]:uppercase [&>h3]:tracking-wider [&>h3]:text-slate-300 [&_details]:border-b [&_details]:border-white/[0.06] [&_details]:py-3 [&_summary]:text-sm [&_summary]:font-bold [&_summary]:text-cyan-200 [&_p]:pt-3 [&_p]:text-sm [&_p]:leading-6 [&_p]:text-slate-400"><h3>Özel koşullar ve açıklamalar</h3><div>{program.kosulList.map((condition, index) => <details key={`${Object.keys(condition)[0]}-${index}`}><summary>Koşul {Object.keys(condition)[0]}</summary><p>{Object.values(condition)[0]}</p></details>)}</div></section>}
    <section className="mt-6 rounded-2xl border border-white/[0.07] bg-slate-950/25 p-4 sm:p-5 [&>header]:flex [&>header]:items-center [&>header]:justify-between [&>header]:gap-4 [&_h3]:text-sm [&_h3]:font-black [&_h3]:uppercase [&_h3]:tracking-wider [&_h3]:text-slate-300 [&_p]:mt-1 [&_p]:text-xs [&_p]:text-slate-600"><header><div><h3>Son yerleşen adayın netleri</h3><p>Canlı YÖK Atlas API</p></div><button className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-xl border px-3.5 py-2 text-sm font-bold transition duration-200 focus-visible:ring-4 focus-visible:ring-cyan-400/15 disabled:cursor-not-allowed disabled:opacity-50 border-slate-700/80 bg-slate-900/70 text-slate-300 hover:border-slate-600 hover:bg-slate-800 hover:text-white" disabled={netLoading} onClick={loadNetRows}>{netLoading ? "Yükleniyor…" : netRows.length ? "Yenile" : "Netleri getir"}</button></header>{netRows.length > 0 && <div className="mt-5 space-y-3 [&>article]:rounded-2xl [&>article]:border [&>article]:border-white/[0.07] [&>article]:bg-slate-900/60 [&>article]:p-4 [&>article>header]:mb-3 [&>article>header]:flex [&>article>header]:items-center [&>article>header]:justify-between [&>article>header]:gap-3 [&>article>header]:text-sm [&>article>header>b]:text-cyan-200 [&>article>header>span]:text-xs [&>article>header>span]:text-slate-500 [&>article>div]:grid [&>article>div]:grid-cols-2 [&>article>div]:gap-2 sm:[&>article>div]:grid-cols-3 lg:[&>article>div]:grid-cols-5 [&>article>div>span]:rounded-xl [&>article>div>span]:bg-slate-950/50 [&>article>div>span]:p-3 [&_small]:block [&_small]:text-[9px] [&_small]:font-bold [&_small]:uppercase [&_small]:text-slate-600">{netRows.map((row, index) => <article key={`${pick(row, "yil")}-${index}`}><header><b>{pick(row, "yil") || "—"}</b><span>Taban puan: {fmtScore(num(pick(row, "tabanPuan", "taban_puan")))} · OBP: {fmtScore(num(pick(row, "obp")))}</span></header><div>{[
      ["TYT Türkçe", "tytTrkNet", "tyt_trk_net"], ["TYT Sosyal", "tytSosNet", "tyt_sos_net"], ["TYT Matematik", "tytMatNet", "tyt_mat_net"], ["TYT Fen", "tytFenNet", "tyt_fen_net"], ["AYT Matematik", "aytMatNet", "ayt_mat_net"], ["AYT Fizik", "aytFizNet", "ayt_fiz_net"], ["AYT Kimya", "aytKimNet", "ayt_kim_net"], ["AYT Biyoloji", "aytBioNet", "ayt_bio_net"], ["AYT Edebiyat", "aytTdeNet", "ayt_tde_net"], ["YDT", "ydtYdilNet", "ydt_ydil_net"]
    ].map(([label, firstKey, secondKey]) => { const value = num(pick(row, firstKey, secondKey)); return value == null ? null : <span key={label}><small>{label}</small><b>{value.toFixed(2)}</b></span>; })}</div></article>)}</div>}</section>
    <p className="mx-auto mt-5 max-w-4xl text-center text-xs leading-5 text-slate-600">Risk etiketi yalnızca aday sıralaman ile son yıl taban sırasını karşılaştırır; kesin yerleşme olasılığı değildir. Tercihlerini ÖSYM kılavuzundan doğrula.</p>
  </Modal>;
}
